name: CI jobs
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    container: nvidia/cuda:10.1-base-ubuntu18.04
    strategy:
      matrix:
        ext: ["", -mkl, -gpu, -mkl-gpu]
    steps:
      - name: Install environment
        shell: bash
        run: |
          CUDA=10.1
          CUDNN=7.6.4.38-1
          apt-get update
          apt-get install -y --no-install-recommends \
            build-essential \
            cuda-command-line-tools-${CUDA/./-} \
            cuda-cudart-dev-${CUDA/./-} \
            cuda-cufft-dev-${CUDA/./-} \
            cuda-curand-dev-${CUDA/./-} \
            cuda-cusolver-dev-${CUDA/./-} \
            cuda-cusparse-dev-${CUDA/./-} \
            cuda-nvrtc-${CUDA/./-} \
            cuda-nvrtc-dev-${CUDA/./-} \
            curl \
            git \
            libcublas10=10.2.1.243-1 \
            libcublas-dev=10.2.1.243-1 \
            libcudnn7-dev=${CUDNN}+cuda${CUDA} \
            libcudnn7=${CUDNN}+cuda${CUDA} \
            libcurl3-dev \
            libfreetype6-dev \
            libiomp5-dev \
            libhdf5-serial-dev \
            libzmq3-dev \
            openjdk-8-jdk \
            patch \
            pkg-config \
            python3 \
            python3-dev \
            python3-pip \
            rsync \
            software-properties-common \
            swig \
            unzip \
            virtualenv \
            wget \
            zip \
            zlib1g-dev


          pip3 --no-cache-dir install setuptools

          ln -s $(which python3) /usr/local/bin/python
          pip3 --no-cache-dir install \
            Pillow \
            h5py \
            keras_preprocessing \
            matplotlib \
            mock \
            numpy \
            scipy \
            sklearn \
            pandas \
            future \
            portpicker

          export LANG=C.UTF-8

          BAZEL_VERSION=2.0.0
          mkdir /bazel && \
            wget -O /bazel/installer.sh "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh" && \
            wget -O /bazel/LICENSE.txt "https://raw.githubusercontent.com/bazelbuild/bazel/master/LICENSE" && \
            chmod +x /bazel/installer.sh && \
            /bazel/installer.sh && \
            rm -f /bazel/installer.sh

          echo Downloading Maven
          curl -L https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz -o $HOME/apache-maven-3.6.3-bin.tar.gz
          tar xzf $HOME/apache-maven-3.6.3-bin.tar.gz -C /opt/
          ln -sf /opt/apache-maven-3.6.3/bin/mvn /usr/bin/mvn

      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git --version
          gcc --version
          mvn -version
          bazel version
          sed -i.bak -e "s/0.1.0-SNAPSHOT/0.1.0-PELTARION-${{ github.sha }}/" `find . -name 'pom.xml'`
          mvn clean install -B -U -e -Djavacpp.platform=linux-x86_64 -Djavacpp.platform.extension=${{ matrix.ext }}
      - name: Upload artifact
        uses:  actions/upload-artifact@v2
        with:
          name: linux-jars${{ matrix.ext }}
          path: /root/.m2/repository/org/tensorflow/**/*
  macosx-x86_64:
    runs-on: macos-latest
    strategy:
      matrix:
        ext: ["", -mkl]
    steps:
      - name: Install environment
        run: |
          python3 -m pip install six
          echo Downloading Bazel
          curl -L https://github.com/bazelbuild/bazel/releases/download/2.0.0/bazel-2.0.0-installer-darwin-x86_64.sh -o bazel.sh --retry 10
          bash bazel.sh
          brew install libomp
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git --version
          clang --version
          mvn -version
          bazel version
          mkdir -p $HOME/.m2
          sed -i .bak -e "s/0.1.0-SNAPSHOT/0.1.0-PELTARION-${{ github.sha }}/"  `find . -name 'pom.xml'`
          mvn clean install -B -U -e -Djavacpp.platform=macosx-x86_64 -Djavacpp.platform.extension=${{ matrix.ext }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: macos-jars${{ matrix.ext }}
          path: /Users/runner/.m2/repository/org/tensorflow/**/*

  # redeploy:
  #   needs: [linux-x86_64, macosx-x86_64]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v1
  #     - name: Setup Java
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 1.8
  #     - name: Download Artifacts
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: macos-jars
  #     - name: Download Artifacts
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: macos-jars-mkl
  #     - name: Redeploy snapshot artifacts
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       run: |
  #         cd tensorflow-core
  #         mvn dependency:resolve -Predeploy -N -B -U -e -Djavacpp.platform.custom -Djavacpp.platform.linux-x86_64 -Djavacpp.platform.macosx-x86_64
  #         cp $HOME/.m2/repository/org/tensorflow/tensorflow-core-api/*-SNAPSHOT/tensorflow-core-api-*-SNAPSHOT*.jar .
  #         for f in *.jar; do
  #           if [[ $f =~ tensorflow-core-api-.*SNAPSHOT-(.*).jar ]]; then
  #              [[ -n $FILES ]] && FILES=$FILES,$f || FILES=$f
  #              [[ -n $TYPES ]] && TYPES=$TYPES,jar || TYPES=jar
  #              [[ -n $CLASSIFIERS ]] && CLASSIFIERS=$CLASSIFIERS,${BASH_REMATCH[1]} || CLASSIFIERS=${BASH_REMATCH[1]}
  #           fi
  #         done
  #         mvn clean deploy -Predeploy -N -B -U -e -Dfiles=$FILES -Dtypes=$TYPES -Dclassifiers=$CLASSIFIERS
